// Code generated by protoc-gen-go.
// source: spacecraft.proto
// DO NOT EDIT!

/*
Package spacecraft is a generated protocol buffer package.

It is generated from these files:
	spacecraft.proto

It has these top-level messages:
	Empty
	SvnUpParam
	VersionNum
	SvnCheckoutParams
	SvnUpToRevisionParams
	ResponseStr
	SpecifiedCommandParams
	SendFileParams
*/
package spacecraft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// live
type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// svnUp params
type SvnUpParam struct {
	Dir string `protobuf:"bytes,1,opt,name=dir" json:"dir,omitempty"`
}

func (m *SvnUpParam) Reset()                    { *m = SvnUpParam{} }
func (m *SvnUpParam) String() string            { return proto.CompactTextString(m) }
func (*SvnUpParam) ProtoMessage()               {}
func (*SvnUpParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// svnUp response
type VersionNum struct {
	Version int32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
}

func (m *VersionNum) Reset()                    { *m = VersionNum{} }
func (m *VersionNum) String() string            { return proto.CompactTextString(m) }
func (*VersionNum) ProtoMessage()               {}
func (*VersionNum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// svnCheckout params
type SvnCheckoutParams struct {
	SvnUrl string `protobuf:"bytes,1,opt,name=svnUrl" json:"svnUrl,omitempty"`
	Dir    string `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
}

func (m *SvnCheckoutParams) Reset()                    { *m = SvnCheckoutParams{} }
func (m *SvnCheckoutParams) String() string            { return proto.CompactTextString(m) }
func (*SvnCheckoutParams) ProtoMessage()               {}
func (*SvnCheckoutParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// svnUpToRevision params
type SvnUpToRevisionParams struct {
	Dir     string `protobuf:"bytes,1,opt,name=dir" json:"dir,omitempty"`
	Version int32  `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (m *SvnUpToRevisionParams) Reset()                    { *m = SvnUpToRevisionParams{} }
func (m *SvnUpToRevisionParams) String() string            { return proto.CompactTextString(m) }
func (*SvnUpToRevisionParams) ProtoMessage()               {}
func (*SvnUpToRevisionParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ResponseStr struct {
	String_ string `protobuf:"bytes,1,opt,name=string" json:"string,omitempty"`
}

func (m *ResponseStr) Reset()                    { *m = ResponseStr{} }
func (m *ResponseStr) String() string            { return proto.CompactTextString(m) }
func (*ResponseStr) ProtoMessage()               {}
func (*ResponseStr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// specifiedCommand params
type SpecifiedCommandParams struct {
	Command string `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	Dir     string `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
}

func (m *SpecifiedCommandParams) Reset()                    { *m = SpecifiedCommandParams{} }
func (m *SpecifiedCommandParams) String() string            { return proto.CompactTextString(m) }
func (*SpecifiedCommandParams) ProtoMessage()               {}
func (*SpecifiedCommandParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// sendFile params
type SendFileParams struct {
	RelativePath string `protobuf:"bytes,1,opt,name=relativePath" json:"relativePath,omitempty"`
	FileContent  []byte `protobuf:"bytes,2,opt,name=fileContent,proto3" json:"fileContent,omitempty"`
}

func (m *SendFileParams) Reset()                    { *m = SendFileParams{} }
func (m *SendFileParams) String() string            { return proto.CompactTextString(m) }
func (*SendFileParams) ProtoMessage()               {}
func (*SendFileParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*Empty)(nil), "spacecraft.Empty")
	proto.RegisterType((*SvnUpParam)(nil), "spacecraft.SvnUpParam")
	proto.RegisterType((*VersionNum)(nil), "spacecraft.VersionNum")
	proto.RegisterType((*SvnCheckoutParams)(nil), "spacecraft.SvnCheckoutParams")
	proto.RegisterType((*SvnUpToRevisionParams)(nil), "spacecraft.SvnUpToRevisionParams")
	proto.RegisterType((*ResponseStr)(nil), "spacecraft.ResponseStr")
	proto.RegisterType((*SpecifiedCommandParams)(nil), "spacecraft.SpecifiedCommandParams")
	proto.RegisterType((*SendFileParams)(nil), "spacecraft.sendFileParams")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Spacecraft service

type SpacecraftClient interface {
	SvnUp(ctx context.Context, in *SvnUpParam, opts ...grpc.CallOption) (*VersionNum, error)
	SvnCheckout(ctx context.Context, in *SvnCheckoutParams, opts ...grpc.CallOption) (*VersionNum, error)
	SvnUpToRevision(ctx context.Context, in *SvnUpToRevisionParams, opts ...grpc.CallOption) (*VersionNum, error)
	SvnInfo(ctx context.Context, in *SvnUpParam, opts ...grpc.CallOption) (*ResponseStr, error)
	SpecifiedCommand(ctx context.Context, in *SpecifiedCommandParams, opts ...grpc.CallOption) (*ResponseStr, error)
	ComplexCommand(ctx context.Context, in *SpecifiedCommandParams, opts ...grpc.CallOption) (*ResponseStr, error)
	SendFile(ctx context.Context, in *SendFileParams, opts ...grpc.CallOption) (*ResponseStr, error)
	GetFileList(ctx context.Context, in *SvnUpParam, opts ...grpc.CallOption) (*ResponseStr, error)
	Live(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResponseStr, error)
}

type spacecraftClient struct {
	cc *grpc.ClientConn
}

func NewSpacecraftClient(cc *grpc.ClientConn) SpacecraftClient {
	return &spacecraftClient{cc}
}

func (c *spacecraftClient) SvnUp(ctx context.Context, in *SvnUpParam, opts ...grpc.CallOption) (*VersionNum, error) {
	out := new(VersionNum)
	err := grpc.Invoke(ctx, "/spacecraft.Spacecraft/svnUp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spacecraftClient) SvnCheckout(ctx context.Context, in *SvnCheckoutParams, opts ...grpc.CallOption) (*VersionNum, error) {
	out := new(VersionNum)
	err := grpc.Invoke(ctx, "/spacecraft.Spacecraft/svnCheckout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spacecraftClient) SvnUpToRevision(ctx context.Context, in *SvnUpToRevisionParams, opts ...grpc.CallOption) (*VersionNum, error) {
	out := new(VersionNum)
	err := grpc.Invoke(ctx, "/spacecraft.Spacecraft/svnUpToRevision", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spacecraftClient) SvnInfo(ctx context.Context, in *SvnUpParam, opts ...grpc.CallOption) (*ResponseStr, error) {
	out := new(ResponseStr)
	err := grpc.Invoke(ctx, "/spacecraft.Spacecraft/svnInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spacecraftClient) SpecifiedCommand(ctx context.Context, in *SpecifiedCommandParams, opts ...grpc.CallOption) (*ResponseStr, error) {
	out := new(ResponseStr)
	err := grpc.Invoke(ctx, "/spacecraft.Spacecraft/specifiedCommand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spacecraftClient) ComplexCommand(ctx context.Context, in *SpecifiedCommandParams, opts ...grpc.CallOption) (*ResponseStr, error) {
	out := new(ResponseStr)
	err := grpc.Invoke(ctx, "/spacecraft.Spacecraft/complexCommand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spacecraftClient) SendFile(ctx context.Context, in *SendFileParams, opts ...grpc.CallOption) (*ResponseStr, error) {
	out := new(ResponseStr)
	err := grpc.Invoke(ctx, "/spacecraft.Spacecraft/sendFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spacecraftClient) GetFileList(ctx context.Context, in *SvnUpParam, opts ...grpc.CallOption) (*ResponseStr, error) {
	out := new(ResponseStr)
	err := grpc.Invoke(ctx, "/spacecraft.Spacecraft/getFileList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spacecraftClient) Live(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResponseStr, error) {
	out := new(ResponseStr)
	err := grpc.Invoke(ctx, "/spacecraft.Spacecraft/live", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Spacecraft service

type SpacecraftServer interface {
	SvnUp(context.Context, *SvnUpParam) (*VersionNum, error)
	SvnCheckout(context.Context, *SvnCheckoutParams) (*VersionNum, error)
	SvnUpToRevision(context.Context, *SvnUpToRevisionParams) (*VersionNum, error)
	SvnInfo(context.Context, *SvnUpParam) (*ResponseStr, error)
	SpecifiedCommand(context.Context, *SpecifiedCommandParams) (*ResponseStr, error)
	ComplexCommand(context.Context, *SpecifiedCommandParams) (*ResponseStr, error)
	SendFile(context.Context, *SendFileParams) (*ResponseStr, error)
	GetFileList(context.Context, *SvnUpParam) (*ResponseStr, error)
	Live(context.Context, *Empty) (*ResponseStr, error)
}

func RegisterSpacecraftServer(s *grpc.Server, srv SpacecraftServer) {
	s.RegisterService(&_Spacecraft_serviceDesc, srv)
}

func _Spacecraft_SvnUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SvnUpParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SpacecraftServer).SvnUp(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Spacecraft_SvnCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SvnCheckoutParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SpacecraftServer).SvnCheckout(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Spacecraft_SvnUpToRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SvnUpToRevisionParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SpacecraftServer).SvnUpToRevision(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Spacecraft_SvnInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SvnUpParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SpacecraftServer).SvnInfo(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Spacecraft_SpecifiedCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SpecifiedCommandParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SpacecraftServer).SpecifiedCommand(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Spacecraft_ComplexCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SpecifiedCommandParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SpacecraftServer).ComplexCommand(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Spacecraft_SendFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SendFileParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SpacecraftServer).SendFile(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Spacecraft_GetFileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SvnUpParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SpacecraftServer).GetFileList(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Spacecraft_Live_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(SpacecraftServer).Live(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Spacecraft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spacecraft.Spacecraft",
	HandlerType: (*SpacecraftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "svnUp",
			Handler:    _Spacecraft_SvnUp_Handler,
		},
		{
			MethodName: "svnCheckout",
			Handler:    _Spacecraft_SvnCheckout_Handler,
		},
		{
			MethodName: "svnUpToRevision",
			Handler:    _Spacecraft_SvnUpToRevision_Handler,
		},
		{
			MethodName: "svnInfo",
			Handler:    _Spacecraft_SvnInfo_Handler,
		},
		{
			MethodName: "specifiedCommand",
			Handler:    _Spacecraft_SpecifiedCommand_Handler,
		},
		{
			MethodName: "complexCommand",
			Handler:    _Spacecraft_ComplexCommand_Handler,
		},
		{
			MethodName: "sendFile",
			Handler:    _Spacecraft_SendFile_Handler,
		},
		{
			MethodName: "getFileList",
			Handler:    _Spacecraft_GetFileList_Handler,
		},
		{
			MethodName: "live",
			Handler:    _Spacecraft_Live_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x94, 0xcf, 0xaf, 0xd2, 0x40,
	0x10, 0x80, 0x7d, 0x4f, 0x7e, 0xe8, 0x94, 0x20, 0x6c, 0x22, 0x12, 0x12, 0x0d, 0x6e, 0xa2, 0xf1,
	0xc4, 0x41, 0xbd, 0x98, 0x68, 0xa2, 0xa9, 0x92, 0x98, 0x18, 0xd4, 0xa2, 0xdc, 0x6b, 0xbb, 0x85,
	0x8d, 0xed, 0xee, 0x66, 0x77, 0x69, 0xf4, 0x7f, 0xf7, 0xe0, 0x76, 0x69, 0x69, 0x17, 0xb0, 0x07,
	0xf3, 0x6e, 0xcc, 0x64, 0xe6, 0x9b, 0x61, 0xbf, 0x01, 0x18, 0x29, 0x11, 0x46, 0x24, 0x92, 0x61,
	0xa2, 0x17, 0x42, 0x72, 0xcd, 0x11, 0xd4, 0x19, 0xdc, 0x87, 0xee, 0x87, 0x4c, 0xe8, 0xdf, 0xf8,
	0x11, 0xc0, 0x3a, 0x67, 0xdf, 0xc5, 0x97, 0x50, 0x86, 0x19, 0x1a, 0xc1, 0xed, 0x98, 0xca, 0xe9,
	0xd5, 0xfc, 0xea, 0xd9, 0xdd, 0xa0, 0xf8, 0x88, 0x9f, 0x02, 0x6c, 0x88, 0x54, 0x94, 0xb3, 0xd5,
	0x3e, 0x43, 0x53, 0xe8, 0xe7, 0x87, 0xc8, 0xd6, 0x74, 0x83, 0x2a, 0xc4, 0x6f, 0x60, 0x6c, 0x38,
	0xfe, 0x8e, 0x44, 0x3f, 0xf9, 0x5e, 0x5b, 0x9a, 0x42, 0x13, 0xe8, 0x29, 0x03, 0x97, 0x69, 0x49,
	0x2c, 0xa3, 0x6a, 0xcc, 0x75, 0x3d, 0xc6, 0x87, 0xfb, 0x76, 0x8d, 0x6f, 0x3c, 0x20, 0x39, 0x2d,
	0x88, 0x25, 0xe2, 0x6c, 0xa3, 0xe6, 0x0e, 0xd7, 0xee, 0x0e, 0x4f, 0xc0, 0x0b, 0x88, 0x12, 0x9c,
	0x29, 0xb2, 0xd6, 0xd2, 0x4e, 0xd7, 0x92, 0xb2, 0xed, 0x71, 0xba, 0x8d, 0xf0, 0x7b, 0x98, 0xac,
	0x05, 0x89, 0x68, 0x42, 0x49, 0xec, 0xf3, 0x2c, 0x0b, 0x59, 0x5c, 0x0e, 0x33, 0xe8, 0xe8, 0x90,
	0x28, 0x5b, 0xaa, 0xf0, 0xc2, 0xc6, 0x1b, 0x18, 0x2a, 0xc2, 0xe2, 0x25, 0x4d, 0x49, 0xd9, 0x8d,
	0x61, 0x20, 0x49, 0x1a, 0x6a, 0x9a, 0x9b, 0x8c, 0xde, 0x95, 0x08, 0x27, 0x87, 0xe6, 0xe0, 0x25,
	0xa6, 0xc3, 0xe7, 0x4c, 0x13, 0xa6, 0x2d, 0x6f, 0x10, 0x34, 0x53, 0xcf, 0xff, 0x74, 0x8c, 0x91,
	0xa3, 0x28, 0xf4, 0x0a, 0xba, 0xc5, 0xa3, 0x09, 0x34, 0x59, 0x34, 0x84, 0xd6, 0xca, 0x66, 0x4e,
	0xbe, 0x56, 0x85, 0x6f, 0xa1, 0x25, 0x78, 0xaa, 0x56, 0x82, 0x1e, 0x9e, 0x00, 0x5c, 0x57, 0x2d,
	0x9c, 0x15, 0xdc, 0x53, 0xae, 0x1b, 0xf4, 0xf8, 0x6c, 0x99, 0x53, 0x71, 0x2d, 0xbc, 0xd7, 0xd0,
	0x37, 0xbc, 0x8f, 0x2c, 0xe1, 0xff, 0xfc, 0x52, 0x0f, 0x9a, 0xf9, 0x86, 0x53, 0xd3, 0xfd, 0xb5,
	0xb8, 0x6c, 0xd7, 0x1e, 0xc2, 0x0e, 0xe6, 0xa2, 0xdb, 0x36, 0xe4, 0x67, 0x18, 0x1a, 0xcf, 0x22,
	0x25, 0xbf, 0x6e, 0x08, 0xf8, 0x0e, 0xee, 0x54, 0xb7, 0x81, 0x66, 0xcd, 0x32, 0xf7, 0x62, 0xda,
	0x10, 0x6f, 0xc1, 0xdb, 0x12, 0x5d, 0xd4, 0x7e, 0xa2, 0x4a, 0xff, 0xcf, 0x43, 0xbd, 0x84, 0x4e,
	0x6a, 0xce, 0x0e, 0x8d, 0x9b, 0x25, 0xf6, 0x47, 0xdf, 0xd2, 0xf5, 0xa3, 0x67, 0xff, 0x2b, 0x5e,
	0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x38, 0xa0, 0x7e, 0x05, 0x3f, 0x04, 0x00, 0x00,
}
